In [30]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('spam.csv')

In [3]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [5]:
df['spam']= df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [6]:
df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [8]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(df.Message,df.spam,test_size=0.2)

In [10]:
X_train.shape

(4457,)

In [11]:
type(X_train)

pandas.core.series.Series

In [12]:
X_train[:5]

3921    FREE>Ringtone! Reply REAL or POLY eg REAL1 1. ...
740     Haha mayb u're rite... U know me well. Da feel...
2045                  I can send you a pic if you like :)
1594    PRIVATE! Your 2003 Account Statement for shows...
1952    Haha... Really oh no... How? Then will they de...
Name: Message, dtype: object

In [13]:
y_train[:5]

3921    1
740     0
2045    0
1594    1
1952    0
Name: spam, dtype: int64

### Count Vectorizer

In [14]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()
X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7778 sparse matrix of type '<class 'numpy.int64'>'
	with 58999 stored elements in Compressed Sparse Row format>

In [20]:
#get the vocabulary
v.get_feature_names_out()[400:450]

array(['2mro', '2mrw', '2mwen', '2nd', '2nhite', '2nite', '2optout', '2p',
       '2price', '2px', '2rcv', '2stop', '2stoptx', '2stoptxt', '2u',
       '2u2', '2watershd', '2waxsto', '2wks', '2wt', '2wu', '2yr', '2yrs',
       '30', '300', '3000', '300603', '300603t', '300p', '3030', '30apr',
       '30ish', '30pp', '30s', '30th', '31', '3100', '310303', '31p',
       '32', '32000', '3230', '326', '33', '350', '3510i', '3650',
       '36504', '3680', '373'], dtype=object)

In [21]:
#shape of the Vocabulary
v.get_feature_names_out().shape

(7778,)

In [22]:
#whole vocabulary
v.vocabulary_

{'free': 2992,
 'ringtone': 5822,
 'reply': 5750,
 'real': 5637,
 'or': 5009,
 'poly': 5328,
 'eg': 2550,
 'real1': 5638,
 'pushbutton': 5543,
 'dontcha': 2422,
 'babygoodbye': 1208,
 'golddigger': 3186,
 'webeburnin': 7451,
 '1st': 328,
 'tone': 6990,
 'and': 970,
 'more': 4612,
 'when': 7503,
 'join': 3858,
 'for': 2951,
 'wk': 7581,
 'haha': 3305,
 'mayb': 4426,
 're': 5625,
 'rite': 5831,
 'know': 3978,
 'me': 4434,
 'well': 7478,
 'da': 2155,
 'feeling': 2819,
 'of': 4927,
 'being': 1324,
 'liked': 4133,
 'by': 1602,
 'someone': 6325,
 'is': 3763,
 'gd': 3104,
 'lor': 4231,
 'faster': 2794,
 'go': 3171,
 'find': 2869,
 'one': 4973,
 'then': 6852,
 'all': 919,
 'gals': 3073,
 'in': 3654,
 'our': 5041,
 'group': 3263,
 'attached': 1140,
 'liao': 4114,
 'can': 1642,
 'send': 6046,
 'you': 7735,
 'pic': 5231,
 'if': 3611,
 'like': 4132,
 'private': 5456,
 'your': 7741,
 '2003': 342,
 'account': 792,
 'statement': 6479,
 'shows': 6164,
 '800': 640,
 'un': 7162,
 'redeemed': 5684,
 'poi

In [23]:
#get the vocabulary of ringtone
v.get_feature_names_out()[5822]

'ringtone'

In [24]:
#convert to numpy array
X_train_np = X_train_cv.toarray()

In [26]:
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [27]:
X_train[:4]

3921    FREE>Ringtone! Reply REAL or POLY eg REAL1 1. ...
740     Haha mayb u're rite... U know me well. Da feel...
2045                  I can send you a pic if you like :)
1594    PRIVATE! Your 2003 Account Statement for shows...
Name: Message, dtype: object

In [28]:
X_train[:4][740] 

"Haha mayb u're rite... U know me well. Da feeling of being liked by someone is gd lor. U faster go find one then all gals in our group attached liao."

In [37]:
np.where(X_train_np[1]!=0)

(array([ 919, 1140, 1324, 1602, 2155, 2794, 2819, 2869, 3073, 3104, 3171,
        3263, 3305, 3654, 3763, 3978, 4114, 4133, 4231, 4426, 4434, 4927,
        4973, 5041, 5625, 5831, 6325, 6852, 7478], dtype=int64),)

In [39]:
X_train_np[1][919]

1

In [40]:
v.get_feature_names_out()[919]

'all'

### Model Building


In [41]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv,y_train)

MultinomialNB()

In [42]:


X_test_cv = v.transform(X_test)

In [44]:
#Prediction

from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       958
           1       0.97      0.95      0.96       157

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [46]:
# Prediction with email text

emails = [
    'WINNER!! As a valued network customer you have been selected to receivea £900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.',
    'I HAVE A DATE ON SUNDAY WITH WILL!!'
]

email_cv =v.transform(emails)

model.predict(email_cv)

array([1, 0], dtype=int64)

### Pipeline to automate the process


In [47]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

In [48]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [50]:
y_pred = clf.predict(X_test)

In [52]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       958
           1       0.97      0.95      0.96       157

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115

